name: samba-container build and test
on:
  push:
    branches:
      - master
  pull_request:

  # Allow for manually running
  workflow_dispatch:

  # Run at 02:42 UTC every Saturday
  schedule:
    - cron: '42 2 * * 6'

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest
    env:
      REPO: crops/samba
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

    steps:
      - uses: actions/checkout@v3

      # Build the image
      - name: build
        run: docker build -t ${REPO} .

      # Test the image
      - name: test
        run: |
          pip install pytest>3.0
          sudo apt-get install -y cifs-utils
          pytest -v

      # Deploy the images
      - name: deploy
        run: bash deploy.sh
